### ISSUE TITLE
Build error: ‘numeric_limits’ is not a member of ‘std’

### ISSUE THREAD

**Issue by NicTanghe** [nokiatech/heif#121]
I get the error:

Build error: ‘numeric_limits’ is not a member of ‘std’

when trying to build on rocky 9.4

**Comment by cylindrical2002** [comment]
i also found that error, look like it can be fixed by adding a #include<limits>

**Comment by NicTanghe** [comment]
Is the pull request merged in the main branch ?
Do you know what pull request it is ?

**Comment by cylindrical2002** [comment]
https://github.com/nokiatech/heif/pull/119
This one
It just add one single line, but it hasn't been merged, may be no one maintains this repository.
You can just add #include<limits> into the code, and u will find the problem is fixed.
